import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import NavbarComponent from './components/Navbar';
import 'tailwindcss/tailwind.css';


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body >
        <NavbarComponent />
        {children}
      </body>
    </html>
  )
}
